// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_GB": &dictionary{index: en_GBIndex, data: en_GBData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
	}
	fallback := language.MustParse("en-GB")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%d books available":   3,
	"%d books available\n": 1,
	"Launching soon!":      4,
	"Welcome!":             2,
	"Welcome!\n":           0,
}

var de_DEIndex = []uint32{ // 6 elements
	0x00000000, 0x00000011, 0x0000004f, 0x0000005b,
	0x00000094, 0x000000a5,
} // Size: 48 bytes

const de_DEData string = "" + // Size: 165 bytes
	"\x04\x00\x01\x0a\x0c\x02Willkommen!\x04\x00\x01\x0a9\x14\x01\x81\x01\x00" +
	"=\x01\x15\x02Ein Buch erhältlich\x00\x1a\x02%[1]d Bücher erhältlich\x02W" +
	"illkommen!\x14\x01\x81\x01\x00=\x01\x15\x02Ein Buch erhältlich\x00\x1a" +
	"\x02%[1]d Bücher erhältlich\x02Bald verfügbar!"

var en_GBIndex = []uint32{ // 6 elements
	0x00000000, 0x0000000e, 0x00000046, 0x0000004f,
	0x00000082, 0x00000092,
} // Size: 48 bytes

const en_GBData string = "" + // Size: 146 bytes
	"\x04\x00\x01\x0a\x09\x02Welcome!\x04\x00\x01\x0a3\x14\x01\x81\x01\x00=" +
	"\x01\x13\x02One book available\x00\x16\x02%[1]d books available\x02Welco" +
	"me!\x14\x01\x81\x01\x00=\x01\x13\x02One book available\x00\x16\x02%[1]d " +
	"books available\x02Launching soon!"

var zh_CNIndex = []uint32{ // 6 elements
	0x00000000, 0x00000012, 0x0000004d, 0x0000005a,
	0x00000090, 0x0000009d,
} // Size: 48 bytes

const zh_CNData string = "" + // Size: 157 bytes
	"\x04\x00\x01\x0a\x0d\x02欢迎光临\x04\x00\x01\x0a6\x14\x01\x81\x01\x00=\x01" +
	"\x14\x02只有1本书可读\x00\x18\x02总共%[1]d本书可读\x02欢迎光临\x14\x01\x81\x01\x00=\x01" +
	"\x14\x02只有1本书可读\x00\x18\x02总共%[1]d本书可读\x02即将启动"

	// Total table size 612 bytes (0KiB); checksum: 2E1CB335
