// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"gowire/02_project/internal/repo"
	"gowire/02_project/internal/service"
	"gowire/02_project/internal/usecase"
)

// Injectors from wire.go:

func NewPostService() (*service.PostService, error) {
	iPostRepo, err := repo.NewPostRepo()
	if err != nil {
		return nil, err
	}
	postUsecaseOption := &usecase.PostUsecaseOption{
		Repo: iPostRepo,
	}
	iPostUsecase, err := usecase.NewPostUsecase(postUsecaseOption)
	if err != nil {
		return nil, err
	}
	postService := &service.PostService{
		Usecase: iPostUsecase,
	}
	return postService, nil
}
